### ISSUE TITLE
New location of https://jira.codehaus.org/browse/MOJO?

### ISSUE THREAD

**Issue by pmv** [mojohaus/extra-enforcer-rules#1]
Do you plan on using github's issue tracker for extra-enforcer-rules going forward?  The plugin page still points to the old location: http://www.mojohaus.org/extra-enforcer-rules/issue-tracking.html

If so, I will move over a ticket I had under https://jira.codehaus.org/browse/MOJO and submit a corresponding pull request.

Thanks

**Comment by Batmat** [comment]
The website is still very out-of-date, so basically yes, every mojos are
gonna use GitHub issues (since anyway the Codehaus JIRA is actually now
unreachable).

Cheers

2015-06-22 21:52 GMT+02:00 pmv <notifications@github.com>:

> Do you plan on using github's issue tracker for extra-enforcer-rules going
> forward? The plugin page still points to the old location:
> http://www.mojohaus.org/extra-enforcer-rules/issue-tracking.html
>
> If so, I will move over a ticket I had under
> https://jira.codehaus.org/browse/MOJO and submit a corresponding pull
> request.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/extra-enforcer-rules/issues/1>.
>



-- 
Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !

**Comment by pmv** [comment]
Sounds good, thanks.
